# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of this app. Must be unique within a project.
name: app

# The runtime the application uses.
type: "python:2.7"

## The hooks executed at various points in the lifecycle of the application.
hooks:
    build: |
      pip install setuptools --upgrade
      pip install -r requirements.txt

      export AUTO_PNG_TO_JPG=True
      export AUTO_WEBP=True
      export UPLOAD_ENABLED=False
      export LOADER='thumbor.loaders.http_loader'
      export DETECTORS=[\'thumbor.detectors.face_detector\',\'thumbor.detectors.feature_detector\']
      export THUMBOR_NUM_PROCESSES=8

      envtpl /app/etc/circus.ini.tpl  --allow-missing --keep-template
      envtpl /app/etc/circus.d/thumbor-circus.ini.tpl  --allow-missing --keep-template

      if [ ! -f /app/thumbor.conf ]; then
        envtpl /app/thumbor.conf.tpl  --allow-missing --keep-template
      fi


# The size of the persistent disk of the application (in MB).
disk: 1024

# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
#relationships:

# The configuration of app when it is exposed to the web.
web:
    commands:
        start: circusd /app/etc/circus.ini
    locations:
        '/':
            passthru: true
            allow: false
        '/test':
            root: 'public'
            index: ['index.html']
            scripts: false
            allow: true



mounts:
    '/data/result_storage':
        source: local
        source_path: 'result_storage'
    '/data/loader':
        source: local
        source_path: 'loader'
    '/data/storage':
        source: local
        source_path: 'storage'
